### ISSUE TITLE
Redundant Like Button

### ISSUE THREAD

**Issue by VonIobro** [mikey1384/twin-kle#2]
![image](https://cloud.githubusercontent.com/assets/61939/20865216/26043e76-ba47-11e6-835d-3de869da673c.png)

In the image above, there is a like button inside the comment <div>. Additionally there is a button-group below that has the same 'like' button. 

Seems redundant?

**Comment by mikey1384** [comment]
So this picture shows a comment and a reply left on that comment. you can
chose to like the original comment, the reply, both or neither. Two like
button point towards different targets.
