### ISSUE TITLE
shared/containers/Home/FeedPanel/index.js and all the subfiles need some refactoring.

### ISSUE THREAD

**Issue by mikey1384** [mikey1384/twin-kle#4]
When I created this whole component I focused on getting it done and not put much effort on making the code readable. Now that I have a lot more work to do with this specific component, I need to refactor it and make it more readable. Would appreciate if anyone would take a look at the code and point out the parts they find unreadable or refactor it themselves.

**Comment by VonIobro** [comment]
Linking file here: https://github.com/mikey1384/twin-kle/blob/master/shared/containers/Home/FeedPanel/index.js
